#!/usr/bin/env python

from stitcher import main
import cv2

img1 = cv2.imread('/home/tibi/catkin_ws/src/stitcher/testImages/pan1.jpeg')
img2 = cv2.imread('/home/tibi/catkin_ws/src/stitcher/testImages/pan2.jpeg')
img_list = [img1, img2]

if __name__ == '__main__':
	main(img_list)

