#!/usr/bin/env python

import cv2
import os, rospkg

# need to change path if testing somewhere else
img1 = cv2.imread('/home/tibi/MarsRover2019/Workspace/src/stitcher/testImages/pan1.jpeg')
img2 = cv2.imread('/home/tibi/MarsRover2019/Workspace/src/stitcher/testImages/pan2.jpeg')

cv2.imshow('Image', img1)
cv2.imshow('Image2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()